---

- name: Install PuppetLabs release DEB for Debian derivates
  apt: 
    deb: "{{ item }}" 
    state: "{{ puppet_package_state }}"
    update_cache: yes
  with_items:
    - "{{ puppet_release_apt_baseurl }}/puppetlabs-release-{{ ansible_distribution_release }}.deb"
  tags:
    - repo

- name: Install puppet via apt
  apt: 
    pkg:   "{{ item }}"
    state: "{{ puppet_package_state }}"
    update_cache: yes
  with_items:
    - "{{ puppet_package_list }}"
  tags:
    - packages
