---

- name: Install PuppetLabs release DEB for Debian derivates
  apt: pkg=puppet state={{ item }} update_cache=yes
  with_items:
    - "{{ puppet_release_rpm_baseurl }}/puppetlabs-release-{{ ansible_distribution_release }}.deb"
  when: ansible_os_family == 'Debian'
  tags:
    - repo
    - install
    - packages

- name: Install puppet via apt
  apt: pkg={{ item }} state={{ puppet_package_state }} update_cache=yes
  with_items:
    - "{{ puppet_package_list }}"
  when: ansible_os_family == 'Debian'
  tags:
    - install
    - packages
