---

- name: Install PuppetLabs release RPM for Fedora or EL derivatives
  yum: name="{{ item }}.noarch.rpm" state={{ puppet_release_package_state }}
  with_items:
    - "{{ puppet_release_rpm_baseurl }}/puppetlabs-release-{% if ansible_distribution == 'Fedora' %}fedora{% else %}el{% endif %}-{{ ansible_distribution_version.split('.')[0] }}"
  when: ansible_os_family == 'RedHat'
  tags:
    - repo
    - install
    - packages

- name: Install puppet via yum
  yum: name={{ item }} state={{ puppet_package_state }}
  with_items:
    - "{{ puppet_package_list }}"
  when: ansible_os_family == 'RedHat'
  tags:
    - install
    - packages
